/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package cbl_project;

/**
 * The main java project class.
 */
public class App {

    public static void main(String[] args) {
        GameplayController gameplayController = new GameplayController();
        gameplayController.startGame();
    }
}
