/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package cbl_project;

import org.junit.jupiter.api.Test;


/*
 * This Java source class was generated by the Gradle 'init' task.
 */
class AppTest {
    @Test void appHasAGreeting() {
        ;
    }
}
